language: java
deploy:
  provider: heroku
  api_key:
    secure: WAgNZtY6t4GTV+hFnAvFuZ99pP4wEIBSv/oTRXr7aHUOYAG6KRRqKGm2z7F8WKB+mY5QMUvr4ibgK6wvXoKyIsskz/o5pHGtoGBMTyLR3LSjIc7+khXhdnIl1GetoxbmeQCC26QuF9pu8Bofg46EEtK+JD/hiovWmHPy5U0rRaw=
  app: ticket-system
  on:
    repo: hhagmans/Ticket-Boys
